apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHIMP_TOKEN
              value: {{ .Values.chimpToken }}
            - name: WORKFLOW_REPO
              value: {{ .Values.workflowRepo }}
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_TLS_CERTDIR
              value: /certs
            - name: DOCKER_CERT_PATH
              value: /certs/client
          volumeMounts:
            - name: certs-client
              mountPath: /certs/client
              readOnly: true
            - name: task-storage
              mountPath: /task_storage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: dind-daemon
          image: docker:20.10.23-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          securityContext: 
            privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker 
            - name: certs-ca
              mountPath: /certs/ca
            - name: certs-client
              mountPath: /certs/client
            - name: task-storage
              mountPath: /task_storage
      volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
      - name: certs-ca
        emptyDir: {}
      - name: certs-client
        emptyDir: {}
      - name: task-storage
        persistentVolumeClaim:
          claimName: task-storage-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
