apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-storage-claim
spec:
  accessModes:
    # civo doesnt support ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
