# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/verus',
                'doc_host': 'https://getdatachimp.github.io',
                'git_url': 'https://github.com/getdatachimp/verus',
                'lib_path': 'verus'},
  'syms': { 'verus.core': { 'verus.core.Task': ('core.html#task', 'verus/core.py'),
                            'verus.core._execute': ('core.html#_execute', 'verus/core.py'),
                            'verus.core._get_automations': ('core.html#_get_automations', 'verus/core.py'),
                            'verus.core._get_source': ('core.html#_get_source', 'verus/core.py'),
                            'verus.core._input_value_to_arg_value': ('core.html#_input_value_to_arg_value', 'verus/core.py'),
                            'verus.core._run_every': ('core.html#_run_every', 'verus/core.py'),
                            'verus.core._task_to_script': ('core.html#_task_to_script', 'verus/core.py'),
                            'verus.core._update_task_status': ('core.html#_update_task_status', 'verus/core.py'),
                            'verus.core.activate': ('core.html#activate', 'verus/core.py'),
                            'verus.core.get_imports_source': ('core.html#get_imports_source', 'verus/core.py')}}}
