# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/verus',
                'doc_host': 'https://getdatachimp.github.io',
                'git_url': 'https://github.com/getdatachimp/verus',
                'lib_path': 'verus'},
  'syms': {'verus.core': {'verus.core.foo': ('core.html#foo', 'verus/core.py')}}}
